name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check changeset
        run: |
          echo '${{github.event.pull_request.merged}}'
          echo '${{github.head_ref}}'
          echo 'aaaa bbbb'